name: conda_psycho_1_dwi_py367
channels:
- conda-forge
# - plotly
dependencies:
- python==3.6.7
- cython==0.29.16
- numpy==1.18.1
- pandas==1.0.3
- joblib==0.14.1
- scipy==1.4.1
- numba==0.48.0
- scikit-learn==0.22.2.post1
# - plotly-orca==1.3.1
# - statsmodels==0.11.1
- dcm2niix==1.0.20190902
- nipype==1.5.0rc1
- pip==20.0.2
- pip:
  - matplotlib==3.2.1
#  - plotly==4.5.4
  - seaborn==0.10.0
  - idna==2.8
  - heudiconv==0.9.0
  - pybids==0.10.2
  - fmriprep-docker==20.2.1 # This automatically does: docker pull poldracklab/fmriprep::20.0.5
  - nibabel==3.0.2
  - nilearn==0.6.2
  - nistats==0.0.1b2
  - nltools==0.3.16
  - HDDM==0.7.6
  - atlasreader==0.1.1 # export QT_DEBUG_PLUGINS=1 # sudo apt-get install libxcb-xinerama0
  - neurora==1.1.3.7
  - qsiprep-container==0.12.2